import React from 'react'
import Image from 'next/image'
import sd from '../public/img/sk_ck.png'
import de from '../public/img/oai_ck.png'

export default function Home() {
  return (
    <>
        <Image 
            src={sd} 
            alt="Picture of an orchid generated by Stable Diffusion" 
        />
        <p>Stable Diffusion</p>
        <Image 
            src={de} 
            alt="Picture of an orchid generated by Dalle2" 
        />
        <p>Dalle2</p>
        <p>Prompt: An expressionist portrait of a wild orchid in a dark forest in the style of Marc Chagall and Wassily Kandinsky</p> 
    </>
  )
}
