import React from "react";
import Image from "next/image";
import sd from "../public/img/sd2_12923.png";
import de from "../public/img/oai2_12923.png";

export default function Home() {
  return (
    <>
      <Image
        className="w-[768px]"
        src={sd}
        alt="Picture of an orchid generated by Stable Diffusion"
      />
      <p>Stable Diffusion</p>
      <Image
        className="w-[768px]"
        src={de}
        alt="Picture of an orchid generated by Dalle2"
      />
      <p>Dalle2</p>
      <p>
        A collage of an orchid blooming on a moonlit night in the style of
        Salvador Dali and Banksy.
      </p>
    </>
  );
}
